import { notFound } from "next/navigation"
import { PROPERTIES } from "@/data/properties"
import { PropertyHero } from "@/components/property/property-hero"
import { PropertyStats } from "@/components/property/property-stats"
import { InvestmentPanel } from "@/components/property/investment-panel"
import { AiAnalysis } from "@/components/property/ai-analysis"
import { Separator } from "@/components/ui/separator"

interface PropertyPageProps {
    params: Promise<{
        id: string
    }>
}

export default async function PropertyPage({ params }: PropertyPageProps) {
    // Await params for dynamic routes in Next.js 15+ (if applicable, but good practice)
    const { id } = await params

    const property = PROPERTIES.find(p => p.id === id) || PROPERTIES[0] // Fallback for demo

    if (!property) {
        notFound()
    }

    return (
        <div className="flex flex-col min-h-screen bg-background">
            <PropertyHero property={property} />

            <div className="container px-4 md:px-8 max-w-screen-2xl py-8">
                <div className="flex flex-col lg:flex-row gap-8">
                    {/* Left Column: Analysis & Details */}
                    <div className="flex-1 space-y-8">
                        <div>
                            <h1 className="text-3xl font-bold tracking-tight mb-2">{property.title}</h1>
                            <p className="text-muted-foreground text-lg">{property.location}</p>
                        </div>

                        <PropertyStats property={property} />

                        <Separator className="my-8" />

                        <div className="prose dark:prose-invert max-w-none">
                            <h3 className="text-xl font-semibold mb-4">About this Opportunity</h3>
                            <p className="text-muted-foreground leading-relaxed">
                                {property.description}
                            </p>
                            <p className="text-muted-foreground leading-relaxed mt-4">
                                This asset tokenization offering represents a fractional interest in the rental income generated by the property.
                                Smart contracts handle the automated distribution of funds to token holders on a monthly basis, providing a seamless passive income experience.
                            </p>
                        </div>

                        <AiAnalysis property={property} />
                    </div>

                    {/* Right Column: Investment Panel */}
                    <div className="w-full lg:w-[380px] shrink-0">
                        <InvestmentPanel property={property} />
                    </div>
                </div>
            </div>
        </div>
    )
}
